### PR TITLE
Fix: empty args causes panic

### LINKED ISSUE #16: 🐛 Empty args causes vm to panic
## 🐛 Bug Report

Calling the wasm vm without args makes it panic.

If more information is needed, @gluax can provide more information 😊 .

### PR DESCRIPTION
**Pull request by gluax**
## Motivation

So go, and don't panic if no args(or bytes or env vars) are sent to the VM. 

Since the go side was the problem, we don't need to update the library files.

## Explanation of Changes

Made the pointers, then have the vars assigned if relevant. 

## Testing

Added a new test to confirm this on both the rust and go side.

## Related PRs and Issues

Closes #16

### CODE REVIEW

File: tallyvm/execute.go [hunk 1]
```diff
@@ -38,10 +38,27 @@ func ExecuteTallyVm(bytes []byte, args []string, envs map[string]string) VmResul
...
+	if len(envs) > 0 {
+		keysPtr = &keys[0]
+		valuesPtr = &values[0]
+	}
+
 	result := C.execute_tally_vm(
-		(*C.uint8_t)(unsafe.Pointer(&bytes[0])), C.uintptr_t(len(bytes)),
-		(**C.char)(unsafe.Pointer(&argsC[0])), C.uintptr_t(len(args)),
-		(**C.char)(unsafe.Pointer(&keys[0])), (**C.char)(unsafe.Pointer(&values[0])), C.uintptr_t(len(envs)),
+		bytesPtr, C.uintptr_t(len(bytes)),
```
Comment (Thomasvdam) [inline tallyvm/execute.go:59]: It's fine if the pointers are not assigned a value? I mean I guess so since the tests pass, it just feels weird 😂

Comment (gluax) [reply tallyvm/execute.go:59]: Yes! In those cases, they are `nil` in `go` or `null` in `c`. Either is fine :).

**Review by FranklinWaller — APPROVED** [review]

**Review by mariocao — APPROVED** [review]
