### PR TITLE
Fix: execution result memory leak

### LINKED ISSUE #61: 🐛 Execution Result is Leaking Memory
## 🐛 Bug Report

The execution result from the tally VM is leaking memory.

## Steps to Reproduce

```
# generate a binary from a go test case
CGO_CFLAGS="-g" CGO_LDFLAGS="-g" go test -run TestTallyBinaryWorks -c -o test_binary
# after that call valgrind on it with a higher num callers
valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --num-callers=50  --log-file=valgrind2.log ./test_binary
```

#### Code snippet to reproduce

It's caused by the execution result clone in `runtime.rs`:  `Ok((execution_result.clone(), exit_code, gas_used))`.

However, even if you remove that , the leak moves up till it eventually hits the `read_to_vec` call in the `execution_result.rs` file.

#### Stack trace & error message

```
==3704883== 220 bytes in 1 blocks are definitely lost in loss record 39 of 81
==3704883==    at 0x48457A8: malloc (vg_replace_malloc.c:446)
==3704883==    by 0x5667719: alloc::raw_vec::RawVecInner<A>::try_allocate_in (in /home/galu/Documents/work/seda/seda-wasm-vm/tallyvm/libseda_tally_vm.x86_64.so)
==3704883==    by 0x4A62047: with_capacity_in<alloc::alloc::Global> (raw_vec.rs:420)
==3704883==    by 0x4A62047: with_capacity_in<u8, alloc::alloc::Global> (raw_vec.rs:192)
==3704883==    by 0x4A62047: with_capacity_in<u8, alloc::alloc::Global> (mod.rs:803)
==3704883==    by 0x4A62047: to_vec<u8, alloc::alloc::Global> (slice.rs:161)
==3704883==    by 0x4A62047: to_vec<u8, alloc::alloc::Global> (slice.rs:110)
==3704883==    by 0x4A62047: to_vec_in<u8, alloc::alloc::Global> (slice.rs:504)
==3704883==    by 0x4A62047: <alloc::vec::Vec<T,A> as core::clone::Clone>::clone (mod.rs:3291)
==3704883==    by 0x49E15E4: internal_run_vm (runtime.rs:168)
==3704883==    by 0x49E15E4: seda_wasm_vm::runtime::start_runtime (runtime.rs:176)
==3704883==    by 0x49D3CB9: _execute_tally_vm (lib.rs:256)
==3704883==    by 0x49D3CB9: execute_tally_vm (lib.rs:207)
==3704883==    by 0x5E18FA: _cgo_e8a972dbd80b_Cfunc_execute_tally_vm (cgo-gcc-prolog:62)
==3704883==    by 0x47C8A3: runtime.asmcgocall.abi0 (asm_amd64.s:923)
==3704883==    by 0xC00018317F: ???
==3704883==    by 0x47AC69: runtime.systemstack.abi0 (asm_amd64.s:514)
==3704883==    by 0x1FFEFFFB17: ???
==3704883==    by 0x47F3BE: runtime.newproc.abi0 (<autogenerated>:1)
==3704883==    by 0x47AB64: runtime.mstart.abi0 (asm_amd64.s:395)
==3704883==    by 0x47AAEE: runtime.rt0_go.abi0 (asm_amd64.s:358)
```

## Expected Behavior

No bytes should be definitely lost when calling valgrind.

## Your Environment

- Rust: v1.85.0
- Golang: go1.24.1 linux/amd64
- OS: Arch Linux x86 64

### PR DESCRIPTION
**Pull request by gluax**
## Motivation

To fix a memory leak.

## Explanation of Changes

- Fixed clippy warnings on some rust code
- Fix the gas used values on the go tests
- For running the vm we `std::mem::take` the value from the context. Which takes that value from the result and replaces with the default value.
- execution result now calls `shrink_to_fit` on the execution result after the host side import is called to ensure no extra bytes are being lost.

## Testing

Valgrind no longer reports definitely lost bytes for any of our go tests :).
```
==3187551== LEAK SUMMARY:
==3187551==    definitely lost: 0 bytes in 0 blocks
==3187551==    indirectly lost: 0 bytes in 0 blocks
==3187551==      possibly lost: 22,400 bytes in 70 blocks
==3187551==    still reachable: 4,612,171 bytes in 965 blocks
==3187551==         suppressed: 0 bytes in 0 blocks
```

## Related PRs and Issues

Someone please upload the updated mac library? :D
Closes #61

### CODE REVIEW

File: tallyvm/execute_test.go [hunk 1]
```diff
@@ -72,7 +72,7 @@ func TestTallyBinaryNoArgs(t *testing.T) {
 	assert.Empty(t, res.Result)
 	assert.NotEmpty(t, res.Stderr)
 	assert.NotEmpty(t, res.Stdout)
-	assert.Equal(t, uint64(5131033418750), res.GasUsed)
+	assert.Equal(t, uint64(12131034728750), res.GasUsed)
```
Comment (Thomasvdam) [inline tallyvm/execute_test.go:75]: How does this change increase the gas cost by such a huge amount? That doesn’t really make sense right?

Comment (gluax) [reply tallyvm/execute_test.go:75]: I'm not sure they were updated before merging to fix-review? Or there were multiple changes to fix-review merged and we only took updated libs from one branch instead of the combined branch?

File: test-vm/src/price_feed_tally.rs [hunk 2]
```diff
@@ -34,7 +34,7 @@ pub fn price_feed_tally() -> Result<()> {
         prices.push(price);
     }
 
-    if prices.len() > 0 {
```
Comment (Thomasvdam) [inline test-vm/src/price_feed_tally.rs:37]: Funny to see this is cheaper in WASM land :D

File: tallyvm/execute_test.go (hunk 1 above)
Comment (Thomasvdam) [reply tallyvm/execute_test.go:75]: That would make more sense than this change affecting the gas 😂 I guess the PR that changed the gas costs didn’t include the compiled binaries

Comment (gluax) [reply tallyvm/execute_test.go:75]: We can double check that to be safe, but yea if this did effect the bytes in any way I would expect them to be less due to shrinking the vec?

**Comment by gluax** [comment]
Not sure why the gas used for the one test is different for me locally...

**Comment by Thomasvdam** [comment]
> Not sure why the gas used for the one test is different for me locally...

I'm guessing it has to do with the rust version used to compile the WASM... If this is correct we should either make sure our local versions are the same as what we use in CI, or we'll have to commit the generated WASM.

**Comment by gluax** [comment]
> > Not sure why the gas used for the one test is different for me locally...
> 
> I'm guessing it has to do with the rust version used to compile the WASM... If this is correct we should either make sure our local versions are the same as what we use in CI, or we'll have to commit the generated WASM.

Ah shoot likely...

**Comment by gluax** [comment]
Ok matching rust version to the CI did not fix the issue.
This makes me think the issue is likely to be a difference in versions of a C lib that wasmer(or some other dep) the vm depends on from my machine to the CI.

Solution: I uploaded the release version of the test-vm.wasm to minimize bytes uploaded, since it was release had to update the bytes again.

... Realizing I should prob wasm-opt it as well so we don't increase the size of the repo by too much.

File: assign_too_much_memory.wat
Comment (Thomasvdam) [inline assign_too_much_memory.wat:1]: I think having the `.wat` file is valuable so we know what the wasm actually does.

**Review by Thomasvdam — APPROVED** [review]
Second pair of 👀
